#@package _group_

exp_name: "satg_data2"
input: "/mnt/aoni04/jsakuma/data/sota/"
output: "./logs/exp"
lang: "ctc"
mode: 6
epoch: 50
seed: 0
gpuid: 0
batch_size: 1
max_frame: 60
threshold1: 0.8
threshold2: 0.4
threshold_u: 0.5
rate: 1.0
resume: True
hang: False
dense_flag: False
elan_flag: False
target_type: False
swt_weight: "/mnt/aoni04/katayama/share/SPEC/epoch_20_acc0.887_loss0.266_ut_train.pth"

